# Uncomment the next line to define a global platform for your project
# platform :ios, '13.1'

target 'rush01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for rush01
  pod 'Alamofire'
  pod 'AlamofireSwiftyJSON'
  pod 'GoogleMaps'
  pod 'GoogleMapsDirections'
  pod 'GooglePlaces'
  pod 'GooglePlacesAPI'

end
